name: Build and release FOSS version
on:
  # Rather have it trigger manually currently
  # push:
  #   branches: [foss]
  #   paths-ignore:
  #     - "**/README.md"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-release-foss:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: foss
      - name: Set release version
        run: |
          VER=$(cat pubspec.yaml | grep -o "version:[^:]*" | cut -f 2 -d ":" | cut -f 1 -d "+" | xargs)
          echo "APP_VERSION=$VER" >> $GITHUB_ENV
      - name: Get Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Get pubspec dependencies
        run: flutter pub get
      - name: Build APK
        run: flutter build apk
      - name: Rename APK
        run: mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/obs-blade-${{ env.APP_VERSION }}.apk
      - name: Create GitHub release and upload APK
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.APP_VERSION }}
          target_commitish: foss
          files: build/app/outputs/flutter-apk/obs-blade-${{ env.APP_VERSION }}.apk
